/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:6ea8ec87-59b3-4310-afce-1399b1bc5f80",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_GPYCUKxdz",
    "aws_user_pools_web_client_id": "4nib4n9sjiq68t2ujc1vgrov84",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://2dsvedc7nvhnpenpkwuxiqaa4e.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qa5b75lerjetdpgwikbnhqzgai",
    "aws_user_files_s3_bucket": "amplifyappstoragebucket10549-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
